### ISSUE TITLE
News file requires ascending order of update defs.

### ISSUE THREAD

**Issue by CodeOptimist** [UnlimitedHugs/RimworldHugsLib#60] opened 2020-03-17 14:29 UTC
(First - deeply appreciate HugsLib, thanks so much!)

Not sure if this is a HugsLib or Ludeon change from 1.1, but it's now mandatory to have the earliest update defs at the top of the news file and the latest at the bottom. 

If it's the reverse, LastSeenNews.xml only increments one update at a time and the full news - minus one entry each time - is displayed over and over again.

This is a departure from how it worked in 1.0 where it didn't seem to matter, so it may break some mods. Not sure if this is intentional or an unintentional bug.

(Maybe I'm the only crazy one who liked adding new updates to the top of the file? Not a big deal since I generate the xml from Python.)

**Comment by UnlimitedHugs** [comment] 2020-03-17 16:38
I appreciate the report- definitely not intended behavior.
I have more stuff in the pipeline, so I'll look at it the next time I'm updating.

**Comment by UnlimitedHugs** [comment] 2020-03-24 11:36
Fixed in 7.1.1.

**Closed as completed by UnlimitedHugs** 2020-03-24 11:36 UTC
